version: 2.1
orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.2.6 # Invoke the Heroku orb
  codecov: codecov/codecov@1.0.5 #Invoke the Codecov orb

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run migration
          command: python manage.py migrate
      - run:
          name: Run tests
          command: python manage.py test
      - run:
          name: Run report
          command: coverage run manage.py test
      - codecov/upload:
          conf: .codecov/.codecov.yml

workflows:
  sample:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
